<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SEPackager</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x86</Platforms>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <PublishTrimmed>True</PublishTrimmed>
    <SignAssembly>False</SignAssembly>
    <PlatformTarget>x86</PlatformTarget>
    <PublishAot>False</PublishAot>
    <Company>none</Company>
    <Authors>wick3nd</Authors>
    <Version>0.5.0</Version>
    <Product>SEPackager</Product>
    <RepositoryUrl>https://github.com/wick3nd/SEP-packager</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
    <Optimize>True</Optimize>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DebugType>none</DebugType>
    <Optimize>True</Optimize>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DebugType>none</DebugType>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LZMA-SDK" Version="22.1.1" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.6" />
  </ItemGroup>

</Project>
